/** قائمة لغات Tesseract للاختيار اليدوي في OCR */

export type OcrLangOption = {
  code: string;
  labelAr: string;
  labelNative: string;
};

/** حزم شائعة أولاً، ثم كل لغة منفردة + مع الإنجليزية */
export const OCR_LANG_OPTIONS: OcrLangOption[] = [
  { code: "auto", labelAr: "تلقائي — اكتشاف لغة الصورة", labelNative: "Auto" },
  { code: "deu+eng", labelAr: "ألمانية + إنجليزية", labelNative: "Deutsch + English" },
  { code: "eng", labelAr: "إنجليزية", labelNative: "English" },
  { code: "ara+eng", labelAr: "عربية + إنجليزية", labelNative: "العربية + English" },
  { code: "ara", labelAr: "عربية", labelNative: "العربية" },
  { code: "por+eng", labelAr: "برتغالية + إنجليزية", labelNative: "Português + English" },
  { code: "spa+eng", labelAr: "إسبانية + إنجليزية", labelNative: "Español + English" },
  { code: "fra+eng", labelAr: "فرنسية + إنجليزية", labelNative: "Français + English" },
  { code: "ita+eng", labelAr: "إيطالية + إنجليزية", labelNative: "Italiano + English" },
  { code: "tur+eng", labelAr: "تركية + إنجليزية", labelNative: "Türkçe + English" },
  { code: "nld+eng", labelAr: "هولندية + إنجليزية", labelNative: "Nederlands + English" },
  { code: "pol+eng", labelAr: "بولندية + إنجليزية", labelNative: "Polski + English" },
  { code: "rus+eng", labelAr: "روسية + إنجليزية", labelNative: "Русский + English" },
  { code: "ukr+eng", labelAr: "أوكرانية + إنجليزية", labelNative: "Українська + English" },
  { code: "ces+eng", labelAr: "تشيكية + إنجليزية", labelNative: "Čeština + English" },
  { code: "ron+eng", labelAr: "رومانية + إنجليزية", labelNative: "Română + English" },
  { code: "hun+eng", labelAr: "مجرية + إنجليزية", labelNative: "Magyar + English" },
  { code: "swe+eng", labelAr: "سويدية + إنجليزية", labelNative: "Svenska + English" },
  { code: "nor+eng", labelAr: "نرويجية + إنجليزية", labelNative: "Norsk + English" },
  { code: "dan+eng", labelAr: "دنماركية + إنجليزية", labelNative: "Dansk + English" },
  { code: "fin+eng", labelAr: "فنلندية + إنجليزية", labelNative: "Suomi + English" },
  { code: "ell+eng", labelAr: "يونانية + إنجليزية", labelNative: "Ελληνικά + English" },
  { code: "heb+eng", labelAr: "عبرية + إنجليزية", labelNative: "עברית + English" },
  { code: "fas+eng", labelAr: "فارسية + إنجليزية", labelNative: "فارسی + English" },
  { code: "urd+eng", labelAr: "أردية + إنجليزية", labelNative: "اردو + English" },
  { code: "hin+eng", labelAr: "هندية + إنجليزية", labelNative: "हिन्दी + English" },
  { code: "ben+eng", labelAr: "بنغالية + إنجليزية", labelNative: "বাংলা + English" },
  { code: "chi_sim+eng", labelAr: "صينية مبسطة + إنجليزية", labelNative: "中文(简体) + English" },
  { code: "chi_tra+eng", labelAr: "صينية تقليدية + إنجليزية", labelNative: "中文(繁體) + English" },
  { code: "jpn+eng", labelAr: "يابانية + إنجليزية", labelNative: "日本語 + English" },
  { code: "kor+eng", labelAr: "كورية + إنجليزية", labelNative: "한국어 + English" },
  { code: "tha+eng", labelAr: "تايلاندية + إنجليزية", labelNative: "ไทย + English" },
  { code: "vie+eng", labelAr: "فيتنامية + إنجليزية", labelNative: "Tiếng Việt + English" },
  { code: "ind+eng", labelAr: "إندونيسية + إنجليزية", labelNative: "Indonesia + English" },
  { code: "msa+eng", labelAr: "ماليزية + إنجليزية", labelNative: "Melayu + English" },
  { code: "fil+eng", labelAr: "فلبينية + إنجليزية", labelNative: "Filipino + English" },
  { code: "swa+eng", labelAr: "سواحيلية + إنجليزية", labelNative: "Kiswahili + English" },
  { code: "deu", labelAr: "ألمانية فقط", labelNative: "Deutsch" },
  { code: "por", labelAr: "برتغالية فقط", labelNative: "Português" },
  { code: "spa", labelAr: "إسبانية فقط", labelNative: "Español" },
  { code: "fra", labelAr: "فرنسية فقط", labelNative: "Français" },
  { code: "ita", labelAr: "إيطالية فقط", labelNative: "Italiano" },
  { code: "tur", labelAr: "تركية فقط", labelNative: "Türkçe" },
  { code: "nld", labelAr: "هولندية فقط", labelNative: "Nederlands" },
  { code: "pol", labelAr: "بولندية فقط", labelNative: "Polski" },
  { code: "rus", labelAr: "روسية فقط", labelNative: "Русский" },
  { code: "ukr", labelAr: "أوكرانية فقط", labelNative: "Українська" },
  { code: "ces", labelAr: "تشيكية فقط", labelNative: "Čeština" },
  { code: "ron", labelAr: "رومانية فقط", labelNative: "Română" },
  { code: "hun", labelAr: "مجرية فقط", labelNative: "Magyar" },
  { code: "swe", labelAr: "سويدية فقط", labelNative: "Svenska" },
  { code: "nor", labelAr: "نرويجية فقط", labelNative: "Norsk" },
  { code: "dan", labelAr: "دنماركية فقط", labelNative: "Dansk" },
  { code: "fin", labelAr: "فنلندية فقط", labelNative: "Suomi" },
  { code: "ell", labelAr: "يونانية فقط", labelNative: "Ελληνικά" },
  { code: "heb", labelAr: "عبرية فقط", labelNative: "עברית" },
  { code: "fas", labelAr: "فارسية فقط", labelNative: "فارسی" },
  { code: "urd", labelAr: "أردية فقط", labelNative: "اردو" },
  { code: "hin", labelAr: "هندية فقط", labelNative: "हिन्दी" },
  { code: "ben", labelAr: "بنغالية فقط", labelNative: "বাংলা" },
  { code: "chi_sim", labelAr: "صينية مبسطة فقط", labelNative: "中文(简体)" },
  { code: "chi_tra", labelAr: "صينية تقليدية فقط", labelNative: "中文(繁體)" },
  { code: "jpn", labelAr: "يابانية فقط", labelNative: "日本語" },
  { code: "kor", labelAr: "كورية فقط", labelNative: "한국어" },
  { code: "tha", labelAr: "تايلاندية فقط", labelNative: "ไทย" },
  { code: "vie", labelAr: "فيتنامية فقط", labelNative: "Tiếng Việt" },
  { code: "ind", labelAr: "إندونيسية فقط", labelNative: "Indonesia" },
  { code: "msa", labelAr: "ماليزية فقط", labelNative: "Melayu" },
  { code: "bul+eng", labelAr: "بلغارية + إنجليزية", labelNative: "Български + English" },
  { code: "hrv+eng", labelAr: "كرواتية + إنجليزية", labelNative: "Hrvatski + English" },
  { code: "srp+eng", labelAr: "صربية + إنجليزية", labelNative: "Српски + English" },
  { code: "slk+eng", labelAr: "سلوفاكية + إنجليزية", labelNative: "Slovenčina + English" },
  { code: "slv+eng", labelAr: "سلوفينية + إنجليزية", labelNative: "Slovenščina + English" },
  { code: "lit+eng", labelAr: "ليتوانية + إنجليزية", labelNative: "Lietuvių + English" },
  { code: "lav+eng", labelAr: "لاتفية + إنجليزية", labelNative: "Latviešu + English" },
  { code: "est+eng", labelAr: "إستونية + إنجليزية", labelNative: "Eesti + English" },
  { code: "cat+eng", labelAr: "كتالانية + إنجليزية", labelNative: "Català + English" },
  { code: "aze+eng", labelAr: "أذرية + إنجليزية", labelNative: "Azərbaycan + English" },
  { code: "kaz+eng", labelAr: "كازاخية + إنجليزية", labelNative: "Қазақша + English" },
  { code: "uzb+eng", labelAr: "أوزبكية + إنجليزية", labelNative: "Oʻzbekcha + English" },
  { code: "amh+eng", labelAr: "أمهرية + إنجليزية", labelNative: "አማርኛ + English" },
  { code: "tam+eng", labelAr: "تاملية + إنجليزية", labelNative: "தமிழ் + English" },
  { code: "tel+eng", labelAr: "تيلوغو + إنجليزية", labelNative: "తెలుగు + English" },
  { code: "kan+eng", labelAr: "كنّادا + إنجليزية", labelNative: "ಕನ್ನಡ + English" },
  { code: "mal+eng", labelAr: "مالايالام + إنجليزية", labelNative: "മലയാളം + English" },
  { code: "mar+eng", labelAr: "ماراثي + إنجليزية", labelNative: "मराठी + English" },
  { code: "guj+eng", labelAr: "غوجاراتي + إنجليزية", labelNative: "ગુજરાતી + English" },
  { code: "pan+eng", labelAr: "بنجابية + إنجليزية", labelNative: "ਪੰਜਾਬੀ + English" },
  { code: "nep+eng", labelAr: "نيبالية + إنجليزية", labelNative: "नेपाली + English" },
  { code: "sin+eng", labelAr: "سنهالية + إنجليزية", labelNative: "සිංහල + English" },
  { code: "mya+eng", labelAr: "بورمية + إنجليزية", labelNative: "မြန်မာ + English" },
  { code: "khm+eng", labelAr: "خميرية + إنجليزية", labelNative: "ខ្មែរ + English" },
  { code: "lao+eng", labelAr: "لاوية + إنجليزية", labelNative: "ລາວ + English" },
  { code: "eng+por+spa+fra+deu+ita", labelAr: "لاتينية متعددة (أوروبية)", labelNative: "Multi Latin" },
];
